security:
  debug: false

logging:
  level:
    org.olac: ${LOGGING_LEVEL:INFO}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: '${MAIL_USERNAME}'
    password: '${MAIL_PASSWORD}'
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

olac:
  jwt:
    key: ${JWT_KEY:my-jwt-secret-with-an-even-longer-key}
    timeoutMinutes: 120
  disable-security: ${DISABLE_SECURITY:false}
  max-tickets: 250
  email: ${MAIL_USERNAME}
  paypal:
    api-base: ${PAYPAL_API_BASE}
    client: '${PAYPAL_CLIENT}'
    secret: '${PAYPAL_SECRET}'

  test-data:
    load: ${LOAD_TEST_DATA:false}
    ticket-types:
      - code: type1
        description: Adult
        cost-per-ticket: 50.0
      - code: type2
        description: Child (10 and under)
        cost-per-ticket: 20.0
    reservations:
      - first-name: Darius
        last-name: Makaitis
        email: dmakaitis@gmail.com
        phone: (402) 201-2132
        status: pending-payment
        ticket-counts:
          - ticket-type-code: type1
            count: 3
          - ticket-type-code: type2
            count: 2
      - first-name: Ingrida
        last-name: Pakalniskyte
        email: ingridpak@cox.net
        phone: (402) 613-0725
        status: reserved
        ticket-counts:
          - ticket-type-code: type1
            count: 2
        payments:
          - amount: 100.0
            status: successful
            method: online
            notes: My test note
            entered-by: Test
      - first-name: Alison
        last-name: Joseph
        email: alison@nowhere.com
        status: pending-payment
        ticket-counts:
          - ticket-type-code: type1
            count: 7
          - ticket-type-code: type2
            count: 5
      - first-name: Ralph
        last-name: Barber
        email: ralph@nowhere.com
        status: pending-payment
        ticket-counts:
          - ticket-type-code: type1
            count: 5
          - ticket-type-code: type2
            count: 8
      - first-name: Randall
        last-name: Lawrence
        email: Lawrence@nowhere.com
        status: pending-payment
        ticket-counts:
          - ticket-type-code: type1
            count: 1
          - ticket-type-code: type2
            count: 3
      - first-name: Jeannie
        last-name: Butler
        email: Butler@nowhere.com
        status: pending-payment
        ticket-counts:
          - ticket-type-code: type1
            count: 2
          - ticket-type-code: type2
            count: 4
      - first-name: Latoya
        last-name: Jensen
        email: Jensen@nowhere.com
        status: pending-payment
        ticket-counts:
          - ticket-type-code: type1
            count: 3
          - ticket-type-code: type2
            count: 5
      - first-name: Karl
        last-name: Medina
        email: Medina@nowhere.com
        status: pending-payment
        ticket-counts:
          - ticket-type-code: type1
            count: 9
          - ticket-type-code: type2
            count: 1
      - first-name: Kenneth
        last-name: Castro
        email: Castro@nowhere.com
        status: pending-payment
        ticket-counts:
          - ticket-type-code: type1
            count: 9
          - ticket-type-code: type2
            count: 1
      - first-name: Marlene
        last-name: Scott
        email: Scott@nowhere.com
        status: pending-payment
        ticket-counts:
          - ticket-type-code: type1
            count: 7
      - first-name: Roxanne
        last-name: Walker
        email: Walker@nowhere.com
        status: pending-payment
        ticket-counts:
          - ticket-type-code: type1
            count: 6
          - ticket-type-code: type2
            count: 9
      - first-name: Erica
        last-name: Ballard
        email: Ballard@nowhere.com
        status: pending-payment
        ticket-counts:
          - ticket-type-code: type1
            count: 6
          - ticket-type-code: type2
            count: 4
